version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks:
      - daming-network
    environment:
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: address
      MYSQL_USER: daming
      MYSQL_PASSWORD: 267552
networks:
  daming-network:
    external: false
