version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks:
      - daming-network
    environment:
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: address
      MYSQL_USER: daming
      MYSQL_PASSWORD: 267552
  repository:
    build: ./repository
    command: yarn start
    ports: 
      - 8443:8443
    volumes:
      - ./repository:/app
    depends_on: 
      - db
    networks: 
      - daming-network
  web:
    build: ./web
    command: yarn start
    ports: 
      - 8080:8443
    volumes: 
      - ./web:/app
    depends_on: 
      - repository
    env_file: secrets/web.env
    networks: 
      - daming-network
networks:
  daming-network:
    external: false
