version: '3'
services:
  repository:
    build: .
    working_dir: /app
    command: yarn run start
    volumes:
      - .:/app
    ports:
      - 8443:8443
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
